version: '2.2'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  esdata1:
    driver: local

networks:
  esnet:
